### PR TITLE
Remove all .DS_Store files anywhere in the tree, and __MACOSX directory 

### PR DESCRIPTION
**Pull request by gluneau**
Prevented Out of memory Errors and script exiting silently.

### CODE REVIEW

**Comment by MounaSafiHarab** [comment]
Tested it with 2 f.DS_Store files in the main directory and in one directory within, and it does indeed remove both.

**Review by MounaSafiHarab — APPROVED** [review]

**Review by MounaSafiHarab — CHANGES_REQUESTED** [review]
If no .DS_Store in the zip, we get the extra messages saying rm: missing operand (see below). The execution of the script continues, so not a big deal, but it is worth cleaning the outputted messages. 
I think you first need to check if the file exists, then remove it; or use `| xargs rm -f`

'Testing for database connectivity.
Database is available.
_rm: missing operand
Try 'rm --help' for more information._
You will archive the dir		: ImagingUpload-10-19-aIPv2G'

**Comment by gluneau** [comment]
@MounaSafiHarab new flag added that will fix this issue.

**Comment by MounaSafiHarab** [comment]
@gluneau 
all good now

**Review by MounaSafiHarab — APPROVED** [review]
No more missing operand messages printed on screen with the -f flag

**Pull request merged**
